# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunny Side Up Systems
email: vicente.bolea@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Big Data processing tailored solutions for specific applications.
  Creators and maintainers of Eclipse middleware (DFS|MR|SQL).
  
baseurl: "/sunnysideupIO" # the subpath of your site, e.g. /blog
url: "http://dicl.github.io/sunnysideupIO/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username: vicente.bolea@gmail.com

# Build settings
markdown: kramdown

incremental: True
